// Code generated by protoc-gen-go-lite. DO NOT EDIT.
// protoc-gen-go-lite version: v0.11.0
// source: proto/game/v1/gamestate.proto

package game_v1

import (
	fmt "fmt"
	protobuf_go_lite "github.com/aperturerobotics/protobuf-go-lite"
	io "io"
)

type Save struct {
	unknownFields      []byte
	Fireflies          []*Firefly `protobuf:"bytes,1,rep,name=fireflies,proto3" json:"fireflies,omitempty"`
	BattlesWonTotal    int32      `protobuf:"varint,2,opt,name=battles_won_total,json=battlesWonTotal,proto3" json:"battlesWonTotal,omitempty"`
	BattlesPlayedTotal int32      `protobuf:"varint,3,opt,name=battles_played_total,json=battlesPlayedTotal,proto3" json:"battlesPlayedTotal,omitempty"`
	Money              int32      `protobuf:"varint,4,opt,name=money,proto3" json:"money,omitempty"`
}

func (x *Save) Reset() {
	*x = Save{}
}

func (*Save) ProtoMessage() {}

func (x *Save) GetFireflies() []*Firefly {
	if x != nil {
		return x.Fireflies
	}
	return nil
}

func (x *Save) GetBattlesWonTotal() int32 {
	if x != nil {
		return x.BattlesWonTotal
	}
	return 0
}

func (x *Save) GetBattlesPlayedTotal() int32 {
	if x != nil {
		return x.BattlesPlayedTotal
	}
	return 0
}

func (x *Save) GetMoney() int32 {
	if x != nil {
		return x.Money
	}
	return 0
}

type Firefly struct {
	unknownFields []byte
	Id            int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          int32 `protobuf:"varint,2,opt,name=name,proto3" json:"name,omitempty"`
	Speed         int32 `protobuf:"varint,3,opt,name=speed,proto3" json:"speed,omitempty"`
	Nimbleness    int32 `protobuf:"varint,4,opt,name=nimbleness,proto3" json:"nimbleness,omitempty"`
	BattlesWon    int32 `protobuf:"varint,5,opt,name=battles_won,json=battlesWon,proto3" json:"battlesWon,omitempty"`
	BattlesPlayed int32 `protobuf:"varint,6,opt,name=battles_played,json=battlesPlayed,proto3" json:"battlesPlayed,omitempty"`
}

func (x *Firefly) Reset() {
	*x = Firefly{}
}

func (*Firefly) ProtoMessage() {}

func (x *Firefly) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Firefly) GetName() int32 {
	if x != nil {
		return x.Name
	}
	return 0
}

func (x *Firefly) GetSpeed() int32 {
	if x != nil {
		return x.Speed
	}
	return 0
}

func (x *Firefly) GetNimbleness() int32 {
	if x != nil {
		return x.Nimbleness
	}
	return 0
}

func (x *Firefly) GetBattlesWon() int32 {
	if x != nil {
		return x.BattlesWon
	}
	return 0
}

func (x *Firefly) GetBattlesPlayed() int32 {
	if x != nil {
		return x.BattlesPlayed
	}
	return 0
}

func (m *Save) MarshalVT() (dAtA []byte, err error) {
	if m == nil {
		return nil, nil
	}
	size := m.SizeVT()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBufferVT(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Save) MarshalToVT(dAtA []byte) (int, error) {
	size := m.SizeVT()
	return m.MarshalToSizedBufferVT(dAtA[:size])
}

func (m *Save) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.unknownFields != nil {
		i -= len(m.unknownFields)
		copy(dAtA[i:], m.unknownFields)
	}
	if m.Money != 0 {
		i = protobuf_go_lite.EncodeVarint(dAtA, i, uint64(m.Money))
		i--
		dAtA[i] = 0x20
	}
	if m.BattlesPlayedTotal != 0 {
		i = protobuf_go_lite.EncodeVarint(dAtA, i, uint64(m.BattlesPlayedTotal))
		i--
		dAtA[i] = 0x18
	}
	if m.BattlesWonTotal != 0 {
		i = protobuf_go_lite.EncodeVarint(dAtA, i, uint64(m.BattlesWonTotal))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Fireflies) > 0 {
		for iNdEx := len(m.Fireflies) - 1; iNdEx >= 0; iNdEx-- {
			size, err := m.Fireflies[iNdEx].MarshalToSizedBufferVT(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = protobuf_go_lite.EncodeVarint(dAtA, i, uint64(size))
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *Firefly) MarshalVT() (dAtA []byte, err error) {
	if m == nil {
		return nil, nil
	}
	size := m.SizeVT()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBufferVT(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Firefly) MarshalToVT(dAtA []byte) (int, error) {
	size := m.SizeVT()
	return m.MarshalToSizedBufferVT(dAtA[:size])
}

func (m *Firefly) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.unknownFields != nil {
		i -= len(m.unknownFields)
		copy(dAtA[i:], m.unknownFields)
	}
	if m.BattlesPlayed != 0 {
		i = protobuf_go_lite.EncodeVarint(dAtA, i, uint64(m.BattlesPlayed))
		i--
		dAtA[i] = 0x30
	}
	if m.BattlesWon != 0 {
		i = protobuf_go_lite.EncodeVarint(dAtA, i, uint64(m.BattlesWon))
		i--
		dAtA[i] = 0x28
	}
	if m.Nimbleness != 0 {
		i = protobuf_go_lite.EncodeVarint(dAtA, i, uint64(m.Nimbleness))
		i--
		dAtA[i] = 0x20
	}
	if m.Speed != 0 {
		i = protobuf_go_lite.EncodeVarint(dAtA, i, uint64(m.Speed))
		i--
		dAtA[i] = 0x18
	}
	if m.Name != 0 {
		i = protobuf_go_lite.EncodeVarint(dAtA, i, uint64(m.Name))
		i--
		dAtA[i] = 0x10
	}
	if m.Id != 0 {
		i = protobuf_go_lite.EncodeVarint(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *Save) SizeVT() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Fireflies) > 0 {
		for _, e := range m.Fireflies {
			l = e.SizeVT()
			n += 1 + l + protobuf_go_lite.SizeOfVarint(uint64(l))
		}
	}
	if m.BattlesWonTotal != 0 {
		n += 1 + protobuf_go_lite.SizeOfVarint(uint64(m.BattlesWonTotal))
	}
	if m.BattlesPlayedTotal != 0 {
		n += 1 + protobuf_go_lite.SizeOfVarint(uint64(m.BattlesPlayedTotal))
	}
	if m.Money != 0 {
		n += 1 + protobuf_go_lite.SizeOfVarint(uint64(m.Money))
	}
	n += len(m.unknownFields)
	return n
}

func (m *Firefly) SizeVT() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + protobuf_go_lite.SizeOfVarint(uint64(m.Id))
	}
	if m.Name != 0 {
		n += 1 + protobuf_go_lite.SizeOfVarint(uint64(m.Name))
	}
	if m.Speed != 0 {
		n += 1 + protobuf_go_lite.SizeOfVarint(uint64(m.Speed))
	}
	if m.Nimbleness != 0 {
		n += 1 + protobuf_go_lite.SizeOfVarint(uint64(m.Nimbleness))
	}
	if m.BattlesWon != 0 {
		n += 1 + protobuf_go_lite.SizeOfVarint(uint64(m.BattlesWon))
	}
	if m.BattlesPlayed != 0 {
		n += 1 + protobuf_go_lite.SizeOfVarint(uint64(m.BattlesPlayed))
	}
	n += len(m.unknownFields)
	return n
}

func (m *Save) UnmarshalVT(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return protobuf_go_lite.ErrIntOverflow
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Save: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Save: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Fireflies", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return protobuf_go_lite.ErrIntOverflow
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return protobuf_go_lite.ErrInvalidLength
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return protobuf_go_lite.ErrInvalidLength
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Fireflies = append(m.Fireflies, &Firefly{})
			if err := m.Fireflies[len(m.Fireflies)-1].UnmarshalVT(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BattlesWonTotal", wireType)
			}
			m.BattlesWonTotal = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return protobuf_go_lite.ErrIntOverflow
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BattlesWonTotal |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BattlesPlayedTotal", wireType)
			}
			m.BattlesPlayedTotal = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return protobuf_go_lite.ErrIntOverflow
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BattlesPlayedTotal |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Money", wireType)
			}
			m.Money = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return protobuf_go_lite.ErrIntOverflow
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Money |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := protobuf_go_lite.Skip(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return protobuf_go_lite.ErrInvalidLength
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.unknownFields = append(m.unknownFields, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Firefly) UnmarshalVT(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return protobuf_go_lite.ErrIntOverflow
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Firefly: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Firefly: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return protobuf_go_lite.ErrIntOverflow
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			m.Name = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return protobuf_go_lite.ErrIntOverflow
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Name |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Speed", wireType)
			}
			m.Speed = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return protobuf_go_lite.ErrIntOverflow
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Speed |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Nimbleness", wireType)
			}
			m.Nimbleness = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return protobuf_go_lite.ErrIntOverflow
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Nimbleness |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BattlesWon", wireType)
			}
			m.BattlesWon = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return protobuf_go_lite.ErrIntOverflow
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BattlesWon |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BattlesPlayed", wireType)
			}
			m.BattlesPlayed = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return protobuf_go_lite.ErrIntOverflow
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BattlesPlayed |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := protobuf_go_lite.Skip(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return protobuf_go_lite.ErrInvalidLength
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.unknownFields = append(m.unknownFields, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
