version: "2"

linters:
  default: standard
  enable:
    - depguard
    - gocritic

  settings:
    depguard:
      rules:
        firefly:
          deny:
            - pkg: fmt
              desc: Formatting package is too big

    gocritic:
      enable-all: true
      disabled-checks:
        - importShadow
        - singleCaseSwitch
        - commentedOutCode
