package util

import (
	"github.com/applejag/firefly-go-math/ffrand"
)

func RandomName() Name {
	return Name(
		(uint32(ffrand.Intn(len(names))) << 16) |
			(uint32(ffrand.Intn(len(titles)))),
	)
}

type Name uint32

// Writes the name into the given buffer.
//
// Intended usage:
//
//	var buf [util.LongestPossibleName]byte
//	written := name.WriteInto(buf[:])
//	foobar(string(buf[:written]))
//
// Panics if the "buf" is too small.
func (n Name) WriteInto(buf []byte) int {
	return ConcatInto(buf, names[n>>16], " ", titles[n&0xff])
}

const (
	longestName         = 17
	longestTitle        = 32
	LongestPossibleName = longestName + 1 + longestTitle
)

var names = []string{
	"Gornash",
	"Manslaughter",
	"Shadowblade",
	"Tiddlywinks",
	"Bloodweaver",
	"Darkmaw",
	"Zyrtec ",
	"Fairlight",
	"Ophan",
	"Thunderstorm ",
	"Calculus",
	"Xanthanus",
	"Gram",
	"Stack Overflow",
	"Fearmonger",
	"Lemto",
	"Brucadious",
	"Scar-Bringer",
	"Persidious",
	"Deftanen",
	"Billimus",
	"Schtormack",
	"Brother Elleumpus",
	"Crablunda",
	"Zeck",
	"Blumch",
	"Quemptilla",
	"Ulysses",
	"Caravar",
	"Glorbinizal",
	"Divelda",
	"Blendlewith",
	"Sparabor",
	"Blost",
	"Cornoford",
	"Yufiz",
	"Mike",
	"Thozoth-kan",
	"Mistress Carl",
	"Hrumbert",
	"Calphidious",
	"Snikkit",
	"Farth",
	"Gartholomew",
	"Farsight",
	"Durich",
	"Guinivere",
	"Loretta",
	"Vericyth",
	"Arthur",
	"Sir Blinky",
	"Recort",
	"Juice",
	"Jumblewumble",
	"Scarveld",
	"Theobald",
	"Poppy",
	"Lund",
	"Penumbra",
	"Vanessa",
	"Pilth",
	"Magnolia",
	"Eleanor",
	"Coorish",
	"Babblebrook",
	"Trash",
	"Yent",
	"Mckayleighlalee",
	"Protein Jean",
	"Efemerin",
	"Legaday",
	"Forsythia",
	"Gunglevess",
	"Cecil",
	"Esoteric",
	"Sparwill",
	"Ebony",
	"Mark",
	"Nartooth",
	"Ceitchri",
	"Krogtor",
	"Brutahg",
	"Iovan",
	"Abitar",
	"Brothan",
	"Airwrecka",
	"Lengstrom",
	"Loreal",
	"Baelfrost",
	"Clement",
	"Lexidori",
	"McPhisto",
	"Vextallus",
	"Dominax",
	"Salivathon",
	"Ichoris",
	"Vladriel",
	"Shmexy",
	"Blockbuster",
	"Thalomir",
	"Rexxy",
	"Micycle",
	"Philharmonic",
	"Prestoff",
	"Blumpy",
	"Stephen",
	"Tamale",
	"[REDACTED]",
}

var titles = []string{
	"The Destroyer",
	"Herald of the Void",
	"Frostborn",
	"Foeslinger",
	"of the Rising Bloodmoon",
	"Lord of the Hunt",
	"The Almighty",
	"Lady of Jewels",
	"The Oath of Eternity",
	"Stealer of Gender",
	"Son of Dave",
	"of Sweden",
	"The Recurrent Dream",
	"The Beligerent",
	"Unyielding Foe",
	"The Black Arrow",
	"Who Slays Their Foe",
	"The Delightful",
	"The Sparkleborn",
	"Son of Cry Baby Scott",
	"Head-Kisser",
	"Captain of the Flower Parade",
	"Cranberry Crusher",
	"The Angsty",
	"Of the Feisty Dogs",
	"The Forbidden",
	"Eater of a thousand raisins",
	"Lord of Table Breaking",
	"The Meatripper",
	"Scrumptioner of Belthanag",
	"the Tooth",
	"Of the Jangling Vine",
	"The Opulant",
	"Commander of Death",
	"The Life Bringer",
	"The Tart",
	"the Unready",
	"the Ever-Seeing",
	"Maker of Loves",
	"of Milwaukee",
	"Frost-toes",
	"the Turgid",
	"The Wellpoisoner",
	"The Bodacious",
	"PhD",
	"Of the Shining Spear",
	"Esquire",
	"Junior",
	"The Underkiller",
	"Saludatorian",
	"The Intern",
	"Knight of the Jaw",
	"Lover of Cats",
	"Hero of the Realm",
	"Of the Thorn",
	"Defender of the Realm",
	"Scourge of the Earth",
	"The Bramble",
	"Frogsbane",
	"The Inebriated",
	"Of the Silent Hand",
	"The Wise",
	"The Mildly Inebriated",
	"The Ugly",
	"The Bachelor",
	"The Part Timer",
	"The Skybreaker",
	"The Feeble",
	"Flameblade",
	"Stranger of the Road",
	"The Breathless",
	"The Thorny",
	"The Strangler",
	"Moonblight",
	"Moonblossom",
	"Peasant of the Gods",
	"Way",
	"Sunbane",
	"Master of Shackles",
	"The Tiny",
	"Everlasting ",
	"Eyepoker",
	"the Relentless",
	"the Dateable",
	"Protein Connoisseur ",
	"Steel Bender",
	"Professional Arm Wrestler",
	"the Hairflipper",
	"Monarch of the Mountain",
	"Bae of Salt",
	"Who can believe it's not butter ",
	"Rulebreaker",
	"the Vexing",
	"the Gym Sibling",
	"the Drool Worthy",
	"Rising Star",
	"the Hydrated",
	"Disco Inferno",
	"Minion of the Month",
	"Grunge Enthusiast",
	"the Rapscallion ",
	"Pumpkin Spicer",
	"Jack of all Raids",
	"the Unimpressed",
	"Iron Pumper ",
	"the Pious",
	"Costco Gold Member",
	"the [REDACTED]",
}
